[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/bossagyu"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/bossagyu"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:Bossagyu@yahoo.co.jp"

[social.params]
icon = "messages"